// Cycling 74 Max 6.1b Study

// This code was generated by max6.1b using "jit.gl.pix"

float radians_float(float v);
float eq_float(float v1, float v2);

float radians_float(float v) {
	return 0.017453292519943*v;
}
float eq_float(float v1, float v2) {
	return float(v1 == v2);
}

void mainImage( out vec4 fragColor, in vec2 fragCoord ) {
	
	vec2 cell = fragCoord.xy;
	
	float swiz_538 = cell.y;
	float floor_532 = (floor(swiz_538));
	float swiz_529 = iResolution.y;
	float mul_525 = (swiz_529 * 0.5);
	float mul_526 = (swiz_529 * 0.4);
	float swiz_539 = cell.x;
	float add_535 = (swiz_539 + iTime * 50.0);
	float radians_534 = (radians_float(add_535));
	float sin_533 = (sin(radians_534));
	float mul_527 = (sin_533 * mul_526);
	float add_528 = (mul_527 + mul_525);
	float floor_531 = (floor(add_528));
	float eq_537 = (eq_float(floor_532, floor_531));
	vec4 vec_540 = (vec4(eq_537, eq_537, eq_537, 1.0));
	fragColor = vec_540;
}