// Cycling 74 Max 6.1b Study

// This code was generated by max6.1b using "jit.gl.pix"

void mainImage( out vec4 fragColor, in vec2 fragCoord ) {
		
	vec2 div_361 = (fragCoord.xy / iResolution.xy);
	float swiz_351 = div_361.x;
	float swiz_355 = div_361.y;
	float sin_331 = (sin(iTime));
	float mul_333 = (sin_331 * 0.5);
	float add_335 = (mul_333 + 0.5);
	vec4 vec_347 = (vec4(swiz_351, swiz_355, add_335, 1.0));
	fragColor = vec_347;
}